"""
virtual-pilot.py - Dynamic Avocado suite suite generator and runner
"""

import argparse
import yaml
import os
import sys
import subprocess


def generate_avocado_suite_file(suite_config_path, output_file="avocado_main.py"):
    """Generate the Avocado suite file with hardcoded suite methods."""

    # Load the suite configuration
    try:
        with open(suite_config_path) as f:
            suite_cfg = yaml.safe_load(f)
        suites_to_run = suite_cfg.get("suites_to_run", [])
    except Exception as e:
        print(f"ERROR: Failed to load suite config {suite_config_path}: {e}")
        sys.exit(1)

    if not suites_to_run:
        print("ERROR: No suites specified in suite configuration")
        sys.exit(1)

    print(f"Generating Avocado suite file with {len(suites_to_run)} suites...")

    # Generate the suite file content
    suite_file_content = '''"""
Auto-generated Avocado suite suite
DO NOT EDIT - Generated by virtual-pilot.py
"""

import yaml
from avocado import Test
from orchestrator import run_suite_from_config


'''

    # Generate a suite class for each YAML file
    for idx, suite_yaml in enumerate(suites_to_run, 1):
        suite_name = suite_yaml.split('/')[-1].replace('.yaml', '').replace('.yml', '')
        class_name = f"{suite_name.replace('-', '_').replace('.', '_')}"

        suite_file_content += f'''
class {class_name}(Test):
    """Test case for {suite_yaml}"""

    def test_suite(self):
        suite_yaml = "{suite_yaml}"
        print(f"=========== Running suite: {{suite_yaml}} ===========")
        result, error = run_suite_from_config(suite_yaml)
        print(f"Suite Name: {{suite_yaml}}")

        if result:
            print(f"Status: PASS")
            print(f"Error: NA")
        else:
            print(f"Status: FAIL")
            print(f"Error: {{error}}")
            print(f"========== Completed suite: {{suite_yaml}} ==========")
            self.fail(f"{{error}}")


'''

    # Write the generated suite file
    with open(output_file, 'w') as f:
        f.write(suite_file_content)

    print(f"✓ Generated {output_file} with {len(suites_to_run)} suite classes")
    return output_file, len(suites_to_run)


def run_avocado_suites(suite_file, results_dir="./results", extra_args=None):
    """Run the generated Avocado suite file."""

    cmd = ["avocado", "run", suite_file, "--job-results-dir", results_dir]

    if extra_args:
        cmd.extend(extra_args)

    print(f"\nRunning: {' '.join(cmd)}\n")

    result = subprocess.run(cmd)
    return result.returncode


def main():
    parser = argparse.ArgumentParser(
        description="Virtual Pilot - Dynamic Avocado Suite Suite Runner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 virtual-pilot.py --config config/avocado-suites/guest_sanity.yaml
  python3 virtual-pilot.py --config config/avocado-suites/guest_sanity.yaml --results-dir ./my-results
  python3 virtual-pilot.py --config config/avocado-suites/guest_sanity.yaml --list-only
        """
    )

    parser.add_argument(
        '--config',
        required=True,
        help='Path to the Avocado suite YAML configuration file'
    )

    parser.add_argument(
        '--results-dir',
        default='./results',
        help='Directory to store suite results (default: ./results)'
    )

    parser.add_argument(
        '--output-file',
        default='avocado_main.py',
        help='Generated suite file name (default: avocado_main.py)'
    )

    parser.add_argument(
        '--list-only',
        action='store_true',
        help='Only list suites without running them'
    )

    parser.add_argument(
        '--keep-generated',
        action='store_true',
        help='Keep the generated suite file after running'
    )

    args = parser.parse_args()

    # Validate config file exists
    if not os.path.exists(args.config):
        print(f"ERROR: Config file not found: {args.config}")
        sys.exit(1)

    # Generate the suite file
    suite_file, num_suites = generate_avocado_suite_file(args.config, args.output_file)

    try:
        if args.list_only:
            # Just list the suites
            print(f"\nListing suites in {suite_file}:")
            subprocess.run(["avocado", "list", suite_file])
            return_code = 0
        else:
            # Run the suites
            return_code = run_avocado_suites(suite_file, args.results_dir)
    finally:
        # Clean up generated file unless --keep-generated is specified
        if not args.keep_generated and os.path.exists(suite_file):
            os.remove(suite_file)
            print(f"\n✓ Cleaned up generated file: {suite_file}")

    sys.exit(return_code)


if __name__ == "__main__":
    main()
